#ifndef LAB3_STATS_DEFINES_H
#define LAB3_STATS_DEFINES_H

#define MAX_CURR_XP 100
#define MAX_LEVEL 10
#define INCREMENTIAL_RATE 1.2
#define DEFAULT_MAX_HP 50
#define DEFAULT_MAX_MP 20
#define DEFAULT_BASE_DMG 5
#endif //LAB3_STATS_DEFINES_H
